export const REVIEW_PRODUCT_LIST_REQUEST    = 'REVIEW_PRODUCT_LIST_REQUEST';
export const REVIEW_PRODUCT_LIST_SUCCESS    = 'REVIEW_PRODUCT_LIST_SUCCESS';
export const REVIEW_PRODUCT_LIST_FAIL       = 'REVIEW_PRODUCT_LIST_FAIL';
export const REVIEW_PRODUCT_LIST_RESET      = 'REVIEW_PRODUCT_LIST_RESET';

export const REVIEW_MINE_LIST_REQUEST       = 'REVIEW_MINE_LIST_REQUEST';
export const REVIEW_MINE_LIST_SUCCESS       = 'REVIEW_MINE_LIST_SUCCESS';
export const REVIEW_MINE_LIST_FAIL          = 'REVIEW_MINE_LIST_FAIL';

export const REVIEW_USER_LIST_REQUEST       = 'REVIEW_USER_LIST_REQUEST';
export const REVIEW_USER_LIST_SUCCESS       = 'REVIEW_USER_LIST_SUCCESS';
export const REVIEW_USER_LIST_FAIL          = 'REVIEW_USER_LIST_FAIL';
export const REVIEW_USER_LIST_RESET         = 'REVIEW_USER_LIST_RESET';
